Control.data = {
    infoText: "bblaze control 1.4 template for integrating control, max4live, arduino and midi hardware",
};


	var cssCode = " .button, .slider_stroke, .slider { border-width:10px; } .widget{ opacity: 0.8} #selectedInterface { background: url(http://www.deviantart.com/download/144678141/Green_Techno_Abstract_Wallpape_by_obreakdanceo.jpg)} ";
	var styleElement = document.createElement("style");
	styleElement.type = "text/css";
	styleElement.appendChild(document.createTextNode(cssCode));
	document.getElementsByTagName("head")[0].appendChild(styleElement);

Control.interface = {
    name: "Billie Blaze",
    orientation: "landscape",
    pages: [
[
{
"name": "masterLevel",
"type" : "Slider",
"x" : .01,
"y" : .01,
"width" : .01,
"height" : .8,
"startingValue" : 0,
"min" : 0,
"max" : 1,
"isInverted" : false,
"isVertical" : true,
"protocol" : "OSC",
"address": "/masterLevel",
"color": '#B37A7A',
"strokeColor" : "#939393",
"backgroundColor": "#35363B"
},
// master faders
{
"name" : "Master",
"type" : "Slider",
"x" : .02,
"y" : .01,
"width" : .175,
"height" : .8,
"startingValue" : 0,
"min" : 0,
"max" : 1,
"isInverted" : false,
"isVertical" : true,
"protocol" : "OSC",
"address" : "/Master",
"strokeColor" : "#E6EEF9",
"fillColor" : "#3D6FAA",
"backgroundColor": "#35363B",
},
{
"name" : "EFXRet",
"type" : "MultiSlider",
"numberOfSliders" : 4,
"x" : .21,
"y" : .01,
"width" : .25,
"height" : .8,
"startingValue" : 0,
"min" : 0,
"max" : 1,
"isInverted" : false,
"isVertical" : true,
"protocol" : "OSC",
"address" : "/EFXRet",
"fillColor" : "#1B276F",
"backgroundColor": "#35363B"
},
// MultiTouch
{
"name" : "multi",
"type" : "MultiTouchXY",
"bounds" : [ .48, .01, .51, .5 ],
"isMomentary" : false,
"maxTouches" : 1,
"strokeColor" : "#E6EEF9",
"fillColor" : "#7898C1",
"backgroundColor": "#35363B"
},
],


// page 2


[
//Ch Sliders
{
"name" : "chVol",
"type" : "MultiSlider",
"numberOfSliders" : 9,
"x" : .0,
"y" : .0,
"width" : .6,
"height" : .6,
"startingValue" : 0,
"midiStartingValue" : 0,
"backgroundColor" : "gray",
"strokeColor" : "gray",
"fillColor" : "blue",
"min" : 0,
"max" : 1,
"isInverted" : false,
"isVertical" : true,
"protocol" : "OSC",
"strokeColor" : "#E6EEF9",
"fillColor" : "#3D6FAA",
"backgroundColor": "#35363B",
},
//Channel Mute
{
"name" : "chMute",
"type" : "MultiButton",
"x" : .0,
"y" : .6,
"width" : .6,
"height" : .1,
"rows" : 1,
"columns" : 9,
"shouldLabel":true,
"backgroundColor": "#35363B",
"fillColor" : "#1B276F",
"strokeColor": "#939393",
},
//Channel Select
{
"name" : "chSelect",
"type" : "MultiButton",
"x" : .0,
"y" : .7,
"width" : .6,
"height" : .1,
"rows" : 1,
"columns" : 9,
"shouldLabel":true,
"backgroundColor": "#35363B",
"fillColor" : "#1B276F",
"strokeColor": "#939393",
"ontouchstart" : "control.initChannelScreen(this.childID);"
},


{
	"name" : "chVol",
	"type" : "MultiSlider",
	"numberOfSliders" : 4,
	"x" : .65,
	"y" : .0,
	"width" : .3,
	"height" : .6,
	"startingValue" : 0,
	"midiStartingValue" : 0,
	"backgroundColor" : "gray",
	"strokeColor" : "gray",
	"fillColor" : "blue",
	"min" : 0,
	"max" : 1,
	"isInverted" : false,
	"isVertical" : true,
	"protocol" : "OSC",
	"strokeColor" : "#E6EEF9",
	"fillColor" : "#3D6FAA",
	"backgroundColor": "#35363B",
	},
	//Channel Mute
	{
	"name" : "chMute",
	"type" : "MultiButton",
	"x" : .65,
	"y" : .6,
	"width" : .3,
	"height" : .1,
	"rows" : 1,
	"columns" : 4,
	"shouldLabel":true,
	"backgroundColor": "#35363B",
	"fillColor" : "#1B276F",
	"strokeColor": "#939393",
	},
	//Channel Select
	{
	"name" : "chSelect",
	"type" : "MultiButton",
	"x" : .65,
	"y" : .7,
	"width" : .3,
	"height" : .1,
	"rows" : 1,
	"columns" : 4,
	"shouldLabel":true,
	"backgroundColor": "#35363B",
	"fillColor" : "#1B276F",
	"strokeColor": "#939393",
	"ontouchstart" : "control.initChannelScreen(this.childID);"
	},
	
],

//Page 3 - Electribe 1-4
[
// Channel 1
{
"name" : "et1pit",
"type" : "Knob",
"x" : .0,
"y" : 0,
"width" : .1,
"address": "/et/0/0",
"min": 0,
"max": 127,
},
{
"name" : "et1env",
"type" : "Knob",
"x" : .0,
"y" : .2,
"width" : .1,
"address": "/et/0/1",
"min": 0,
"max": 127,
},
{
"name" : "et1cut",
"type" : "Knob",
"x" : .0,
"y" : .4,
"width" : .1,
"address": "/et/0/2",
"min": 0,
"max": 127,
},
{
"name" : "et1res",
"type" : "Knob",
"x" : .0,
"y" : .6,
"width" : .1,
"address": "/et/0/3",
"min": 0,
"max": 127,
},
{
"name" : "et1vol",
"type" : "Slider",
"x" : .125,
"y" : .0,
"height":.5,
"width": .1,
"isVertical": true,
"isInverted": false,
"address": "/et/0/4",
"min": 0,
"max": 127,
},
{
"name" : "et1send",
"type" : "Button",
"x" : .125,
"y" : .55,
"height":.1,
"width": .1,
"address": "/et/0/5",
"min": 0,
"max": 127,
},
{
"name" : "et1mute",
"type" : "Button",
"x" : .125,
"y" : .65,
"height":.1,
"width": .1,
"address": "/et/0/6",
"min": 0,
"max": 127,
},
// Channel 2
{
"name" : "et2pit",
"type" : "Knob",
"x" : .25,
"y" : 0,
"width" : .1,
"address": "/et/1/0",
"min": 0,
"max": 127,
},
{
"name" : "et2env",
"type" : "Knob",
"x" : .25,
"y" : .2,
"width" : .1,
"address": "/et/1/1",
"min": 0,
"max": 127,
},
{
"name" : "et2cut",
"type" : "Knob",
"x" : .25,
"y" : .4,
"width" : .1,
"address": "/et/1/2",
"min": 0,
"max": 127,
},
{
"name" : "et2res",
"type" : "Knob",
"x" : .25,
"y" : .6,
"width" : .1,
"address": "/et/1/3",
"min": 0,
"max": 127,
},
{
"name" : "et2vol",
"type" : "Slider",
"x" : .375,
"y" : .0,
"height":.5,
"width": .1,
"isVertical": true,
"isInverted": false,
"address": "/et/1/4",
"min": 0,
"max": 127,
},
{
"name" : "et2send",
"type" : "Button",
"x" : .375,
"y" : .55,
"height":.1,
"width": .1,
"address": "/et/1/5",
"min": 0,
"max": 127,
},
{
"name" : "et2mute",
"type" : "Button",
"x" : .375,
"y" : .65,
"height":.1,
"width": .1,
"address": "/et/1/6",
"min": 0,
"max": 127,
},
// Channel 3
{
"name" : "et3pit",
"type" : "Knob",
"x" : .5,
"y" : 0,
"width" : .1,
"address": "/et/2/0",
"min": 0,
"max": 127,
},
{
"name" : "et3env",
"type" : "Knob",
"x" : .5,
"y" : .2,
"width" : .1,
"address": "/et/2/1",
"min": 0,
"max": 127,
},
{
"name" : "et3cut",
"type" : "Knob",
"x" : .5,
"y" : .4,
"width" : .1,
"address": "/et/2/2",
"min": 0,
"max": 127,
},
{
"name" : "et3res",
"type" : "Knob",
"x" : .5,
"y" : .6,
"width" : .1,
"address": "/et/2/3",
"min": 0,
"max": 127,
},
{
"name" : "et3vol",
"type" : "Slider",
"x" : .625,
"y" : .0,
"height":.5,
"width": .1,
"isVertical": true,
"isInverted": false,
"address": "/et/2/4",
"min": 0,
"max": 127,
},
{
"name" : "et3send",
"type" : "Button",
"x" : .625,
"y" : .55,
"height":.1,
"width": .1,
"address": "/et/2/5",
"min": 0,
"max": 127,
},
{
"name" : "et3mute",
"type" : "Button",
"x" : .625,
"y" : .65,
"height":.1,
"width": .1,
"address": "/et/2/6",
"min": 0,
"max": 127,
},
// Channel 4
{
"name" : "et4pit",
"type" : "Knob",
"x" : .75,
"y" : 0,
"width" : .1,
"address": "/et/3/0",
"min": 0,
"max": 127,
},
{
"name" : "et4env",
"type" : "Knob",
"x" : .75,
"y" : .2,
"width" : .1,
"address": "/et/3/1",
"min": 0,
"max": 127,
},
{
"name" : "et4cut",
"type" : "Knob",
"x" : .75,
"y" : .4,
"width" : .1,
"address": "/et/3/2",
"min": 0,
"max": 127,
},
{
"name" : "et4res",
"type" : "Knob",
"x" : .75,
"y" : .6,
"width" : .1,
"address": "/et/3/3",
"min": 0,
"max": 127,
},
{
"name" : "et4vol",
"type" : "Slider",
"x" : .875,
"y" : .0,
"height":.5,
"width": .1,
"isVertical": true,
"isInverted": false,
"address": "/et/3/4",
"min": 0,
"max": 127,
},
{
"name" : "et4send",
"type" : "Button",
"x" : .875,
"y" : .55,
"height":.1,
"width": .1,
"address": "/et/3/5",
"min": 0,
"max": 127,
},
{
"name" : "et4mute",
"type" : "Button",
"x" : .875,
"y" : .65,
"height":.1,
"width": .1,
"address": "/et/3/6",
"min": 0,
"max": 127,
},
],

//Page 5 - virus
[
// Virus Ch 1
{
"name" : "vi1pit",
"type" : "Knob",
"x" : .0,
"y" : 0,
"width" : .1,
},
{
"name" : "vi1env",
"type" : "Knob",
"x" : .0,
"y" : .2,
"width" : .1,
},
{
"name" : "vi1cut",
"type" : "Knob",
"x" : .0,
"y" : .4,
"width" : .1,
},
{
"name" : "vi1res",
"type" : "Knob",
"x" : .0,
"y" : .6,
"width" : .1,
},
{
"name" : "vi1pit",
"type" : "Knob",
"x" : .15,
"y" : 0,
"width" : .1,
},
{
"name" : "vi1env",
"type" : "Knob",
"x" : .15,
"y" : .2,
"width" : .1,
},
{
"name" : "vi1cut",
"type" : "Knob",
"x" : .15,
"y" : .4,
"width" : .1,
},
{
"name" : "vi1res",
"type" : "Knob",
"x" : .15,
"y" : .6,
"width" : .1,
},
{
"name" : "vi1vol",
"type" : "Slider",
"x" : .3,
"y" : .0,
"height":.5,
"width": .1,
"isVertical": true,
"isInverted": false,
},
{
"name" : "vi1send",
"type" : "Button",
"x" : .3,
"y" : .55,
"height":.1,
"width": .1,
},
{
"name" : "vi1mute",
"type" : "Button",
"x" : .3,
"y" : .65,
"height":.1,
"width": .1,
},
// Virus Ch 2
{
"name" : "vi2pit",
"type" : "Knob",
"x" : .5,
"y" : 0,
"width" : .1,
},
{
"name" : "vi2env",
"type" : "Knob",
"x" : .5,
"y" : .2,
"width" : .1,
},
{
"name" : "vi2cut",
"type" : "Knob",
"x" : .5,
"y" : .4,
"width" : .1,
},
{
"name" : "vi2res",
"type" : "Knob",
"x" : .5,
"y" : .6,
"width" : .1,
},
{
"name" : "vi2pit",
"type" : "Knob",
"x" : .65,
"y" : 0,
"width" : .1,
},
{
"name" : "vi2env",
"type" : "Knob",
"x" : .65,
"y" : .2,
"width" : .1,
},
{
"name" : "vi2cut",
"type" : "Knob",
"x" : .65,
"y" : .4,
"width" : .1,
},
{
"name" : "vi2res",
"type" : "Knob",
"x" : .65,
"y" : .6,
"width" : .1,
},
{
"name" : "vi2vol",
"type" : "Slider",
"x" : .85,
"y" : .0,
"height":.5,
"width": .1,
"isVertical": true,
"isInverted": false,
},
{
"name" : "vi2send",
"type" : "Button",
"x" : .85,
"y" : .55,
"height":.1,
"width": .1,
},
{
"name" : "vi2mute",
"type" : "Button",
"x" : .85,
"y" : .65,
"height":.1,
"width": .1,
},
],

[
//channel 1
{
"name" : "ch1SD",
"type" : "Knob",
"x" : .11,
"y" : 0,
"width" : .075,
"address": "/sd/0",
},
{
"name" : "ch1LD",
"type" : "Knob",
"x" : .11,
"y" : .15,
"width" : .075,
"address": "/ld/0",
},
{
"name" : "ch1SR",
"type" : "Knob",
"x" : .11,
"y" : .3,
"width" : .075,
"address": "/sr/0",
},
{
"name" : "ch1LR",
"type" : "Knob",
"x" : .11,
"y" : .45,
"width" : .075,
"address": "/lr/0",
},
//channel 2
{
"name" : "ch2SD",
"type" : "Knob",
"x" : .22,
"y" : 0,
"width" : .075,
"address": "/sd/1",
},
{
"name" : "ch2LD",
"type" : "Knob",
"x" : .22,
"y" : .15,
"width" : .075,
"address": "/ld/1",
},
{
"name" : "ch2SR",
"type" : "Knob",
"x" : .22,
"y" : .3,
"width" : .075,
"address": "/sr/1",
},
{
"name" : "ch2LR",
"type" : "Knob",
"x" : .22,
"y" : .45,
"width" : .075,
"address": "/lr/1",
},
//channel 3
{
"name" : "ch3SD",
"type" : "Knob",
"x" : .33,
"y" : 0,
"width" : .075,
"address": "/sd/2",
},
{
"name" : "ch3LD",
"type" : "Knob",
"x" : .33,
"y" : .15,
"width" : .075,
"address": "/ld/2",
},
{
"name" : "ch3SR",
"type" : "Knob",
"x" : .33,
"y" : .3,
"width" : .075,
"address": "/sr/2",
},
{
"name" : "ch3LR",
"type" : "Knob",
"x" : .33,
"y" : .45,
"width" : .075,
"address": "/lr/2",
},
//channel 4
{
"name" : "ch4SD",
"type" : "Knob",
"x" : .44,
"y" : 0,
"width" : .075,
"address": "/sd/3",
},
{
"name" : "ch4LD",
"type" : "Knob",
"x" : .44,
"y" : .15,
"width" : .075,
"address": "/ld/3",
},
{
"name" : "ch4SR",
"type" : "Knob",
"x" : .44,
"y" : .3,
"width" : .075,
"address": "/sr/3",
},
{
"name" : "ch4LR",
"type" : "Knob",
"x" : .44,
"y" : .45,
"width" : .075,
"address": "/lr/3",
},
//channel 5
{
"name" : "ch5SD",
"type" : "Knob",
"x" : .55,
"y" : 0,
"width" : .075,
"address": "/sd/4",
},
{
"name" : "ch5LD",
"type" : "Knob",
"x" : .55,
"y" : .15,
"width" : .075,
"address": "/ld/4",
},
{
"name" : "ch5SR",
"type" : "Knob",
"x" : .55,
"y" : .3,
"width" : .075,
"address": "/sr/4",
},
{
"name" : "ch5LR",
"type" : "Knob",
"x" : .55,
"y" : .45,
"width" : .075,
"address": "/lr/4",
},
//channel 6
{
"name" : "ch6SD",
"type" : "Knob",
"x" : .66,
"y" : 0,
"width" : .075,
"address": "/sd/5",
},
{
"name" : "ch6LD",
"type" : "Knob",
"x" : .66,
"y" : .15,
"width" : .075,
"address": "/ld/5",
},
{
"name" : "ch6SR",
"type" : "Knob",
"x" : .66,
"y" : .3,
"width" : .075,
"address": "/sr/5",
},
{
"name" : "ch6LR",
"type" : "Knob",
"x" : .66,
"y" : .45,
"width" : .075,
"address": "/lr/5",
},
//channel 7
{
"name" : "ch7SD",
"type" : "Knob",
"x" : .77,
"y" : 0,
"width" : .075,
"address": "/sd/6",
},
{
"name" : "ch7LD",
"type" : "Knob",
"x" : .77,
"y" : .15,
"width" : .075,
"address": "/ld/6",
},
{
"name" : "ch7SR",
"type" : "Knob",
"x" : .77,
"y" : .3,
"width" : .075,
"address": "/sr/6",
},
{
"name" : "ch7LR",
"type" : "Knob",
"x" : .77,
"y" : .45,
"width" : .075,
"address": "/lr/6",
},
//channel 8
{
"name" : "ch8SD",
"type" : "Knob",
"x" : .88,
"y" : 0,
"width" : .075,
"address": "/sd/7",
},
{
"name" : "ch8LD",
"type" : "Knob",
"x" : .88,
"y" : .15,
"width" : .075,
"address": "/ld/7",
},
{
"name" : "ch8SR",
"type" : "Knob",
"x" : .88,
"y" : .3,
"width" : .075,
"address": "/sr/7",
},
{
"name" : "ch8LR",
"type" : "Knob",
"x" : .88,
"y" : .45,
"width" : .075,
"address": "/lr/7",
},
],

    ],

    constants: [
	{
     "name": "tabButton",
     "type": "Button",
     "x": .0,
     "y": .85,
     "width": .09,
     "height": .05,
     "color": "#333",
     "min": 0,
     "max": 1,
     "ontouchstart": "Control.toggleToolbar()",
     "label" : "menu",
 	},
     
     {
     "name": "page0Button",
     "type": "Button",
     "x": .2,
     "y": .85,
     "width": .09,
     "height": .05,
     "color": "#666666",
     "mode": "contact",
     "startingValue": 1,
     "ontouchstart": "Control.changePage(0);",
     "label" : "Master",
     }, {
     "name": "page1Button",
     "type": "Button",
     "x": .3,
     "y": .85,
     "width": .09,
     "height": .05,
     "color": "#ff0",
     "mode": "contact",
     "ontouchstart": "Control.changePage(1);",
     "label": "Mixer",
     },
     {
         "name": "page2Button",
         "type": "Button",
         "x": .4,
         "y": .85,
         "width": .09,
         "height": .05,
         "color": "#ff0",
         "mode": "contact",
         "ontouchstart": "Control.changePage(2);",
         "label": "Electribe",
         },
         {
             "name": "page3Button",
             "type": "Button",
             "x": .5,
             "y": .85,
             "width": .09,
             "height": .05,
             "color": "#ff0",
             "mode": "contact",
             "ontouchstart": "Control.changePage(3);",
             "label": "Virus",
             },
             {
                 "name": "page4Button",
                 "type": "Button",
                 "x": .6,
                 "y": .85,
                 "width": .09,
                 "height": .05,
                 "color": "#ff0",
                 "mode": "contact",
                 "ontouchstart": "Control.changePage(4);",
                 "label": "Effects",
                 },    
                 
     {
    	 "name" : "refreshButton",
    	 "type" : "Button", "mode" : "contact",
    	 "x" : .1,	"y" : .85,
    	 "width" : .09,	"height" : .05,
    	 "ontouchstart" : "Control.interfaceManager.refreshInterface()",
    	 "label":"Refresh"
    	 },
    	 
    ],
};
